### ISSUE TITLE
Babel, sourcemaps, and separate commands: nothing covered

### ISSUE THREAD

**Issue by DaAwesomeP** [SBoudrias/gulp-istanbul#106] opened 2016-10-06 05:22 UTC
I can't get istanbul to check anything. I'm using Babel and souremaps. Is this a result from running the pretest and test parts separately?
```js
gulp.task('static', () => {
  return gulp.src('lib/*.js')
    .pipe(excludeGitignore())
    .pipe(lec()) // gulp-line-ending-corrector
    .pipe(gulp.dest('.'))
})

gulp.task('clean', (callback) => {
  del(['dist/*']).then(() => {
    callback()
  })
})

gulp.task('build', gulp.series('static', 'clean', () => {
  return gulp.src('lib/**/*.js')
    .pipe(sourcemaps.init())
    .pipe(babel())
    .pipe(istanbul())
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('dist'))
}))

gulp.task('test', () => {
  return gulp.src(['test/test-*.js'], { read: false })
    .pipe(mocha({
      reporter: 'spec',
      globals: {
        should: require('should')
      }
    }))
    .pipe(istanbul.writeReports())
})
```
In my CI tests, I run `gulp build` in one stage, and then `gulp test` later on. Here's what I get:
```
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
```

**Comment by SBoudrias** [comment] 2016-10-06 06:29
Does your tests read from the dist files? Because as you're not hooking the requires, then it seems to me you're just loading uninstrumented files.

For es6 support, you should look at either updating your Node version or specifying an [instrumenter supporting es6](https://github.com/SBoudrias/gulp-istanbul#instrumenter)

I'll close this issue as it's not a bug with the gulp-istanbul.

**Closed by SBoudrias** 2016-10-06 06:29 UTC

**Comment by DaAwesomeP** [comment] 2016-10-06 15:49
I'm using ES7 async/wait and ES6 module definitions (instead of CommonJS), so I can't run the tests in vanilla Node v6.7. I have to transpile to generators and CommonJS first. How can I cover the source files and test with the transpiled files?

**Comment by DaAwesomeP** [comment] 2016-10-06 22:17
OK, I got it to work. I guess I didn't completely understand how to cover with ES6/Babel:
```js
const babelConfig = Object.assign(
  JSON.parse(require('fs').readFileSync('.babelrc', 'utf8')),
  { stage: 0 })
gulp.task('pretest', () => {
  return gulp.src('lib/**/*.js')
    .pipe(sourcemaps.init())
    .pipe(istanbul({
      instrumenter: isparta.Instrumenter,
      instrumenterOptions: {
        isparta: { babel: babelConfig }
      },
      includeUntested: true
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('.tmp/'))
})

gulp.task('test', gulp.series('pretest', () => {
  return gulp.src(['test/test-*.js'], { read: false })
    .pipe(mocha({
      reporter: 'spec',
      globals: {
        should: require('should')
      }
    }))
    .pipe(istanbul.writeReports())
}))
```
